# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  update_fastlane
end

platform :ios do
  desc "Description of what the lane does"
  lane :increment_build do 
    increment_build_number
    commit_version_bump
  end

  desc "Test the changes"
  lane :test do 
    scan(
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      destination: "name=iPhone 13 Pro Max,OS=15.4"
   )
  end

  desc "Test the changes 2"
  run_tests(workspace: "Fast.xcworkspace",
            devices: ["iiPhone 14 Pro (16.1)"],
            scheme: "FastTests")
  end

  
end