# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  update_fastlane
end

platform :ios do
  desc "Description of what the lane does"
  lane :increment_build do 
    # increment_build_number
    # commit_version_bump
    increment_build_number
    commit_version_bump()
  end

  desc "Test the changes"
  lane :test do 
    scan(
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      destination: "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro"
   )
  end
end