name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1'

   # - name: Build
   #   run: xcodebuild build -project Fast.xcodeproj -scheme Fast clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: xcodebuild clean build -scheme App -project App.xcodeproj -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro'  
      # fastlane runTest # test # xcodebuild test -project Fast.xcodeproj -scheme Fast clean build -sdk iOS CODE_SIGNING_ALLOWED=No
